# # # Crear usuarios
# # User.destroy_all

# # User.create(
# #               [
# #                 {
# #                   email: 'ariel@liga.cl',
# #                   password: '12345678',
# #                   name: 'ariel',
# #                   last_name: 'alvear',
# #                   drivers_name: 'aialvear',
# #                 },
# #                 {
# #                   email: 'juan@liga.cl',
# #                   password: '12345678',
# #                   name: 'juan',
# #                   last_name: 'perez',
# #                   drivers_name: 'juano',
# #                 },
# #                 {
# #                   email: 'pedro@liga.cl',
# #                   password: '12345678',
# #                   name: 'pedro',
# #                   last_name: 'hernandez',
# #                   drivers_name: 'peter',
# #                 },
# #               ]
# #             )

# User.create(
#   [
#     { email: 'Benjaminseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Benjamin', last_name: 'Salazar', drivers_name: 'RVR_Minchito'  },
#     { email: 'Pauloseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Paulo', last_name: 'Dodero', drivers_name: 'RVR_Paulson'  },
#     { email: 'Matiasseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Matias', last_name: 'Matamala', drivers_name: 'ManUtdFans14'  },
#     { email: 'Nicolasseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Nicolas', last_name: 'Lagos', drivers_name: 'RVR_Nicolas10'  },
#     { email: 'JuanPabloseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'JuanPablo', last_name: 'Morales', drivers_name: 'RPFunky'  },
#     { email: 'Maximilianoseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Maximiliano', last_name: 'Heredia', drivers_name: 'Mazzi1991'  },
#     { email: 'Maximilianoseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Maximiliano', last_name: 'Tomic', drivers_name: 'Maxtomic'  },
#     { email: 'Matiasseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Matias', last_name: 'Pino', drivers_name: 'Matrenox'  },
#     { email: 'Jesusseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Jesus', last_name: 'Rios', drivers_name: 'Pepechuy12'  },
#     { email: 'Alfonsoseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Alfonso', last_name: 'Urbina', drivers_name: 'xAlf0ns07x'  },
#     { email: 'Lucasseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Lucas', last_name: 'Riveras', drivers_name: 'LUKA_THE_PRO'  },
#     { email: 'Cristobalseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Cristobal', last_name: 'Figueroa', drivers_name: 'Crisafm'  },
#     { email: 'Andresseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Andres', last_name: 'Mendez', drivers_name: 'Amendez53444'  },
#     { email: 'Juanseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Juan', last_name: 'Valdivia', drivers_name: 'NazhonxX'  },
#     { email: 'Robertoseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Roberto', last_name: 'Manriquez', drivers_name: 'RoLo-_-gg'  },
#     { email: 'Martinseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Martin', last_name: 'Orellana', drivers_name: 'faZe_Titi'  },
#     { email: 'Rafaelseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Rafael', last_name: 'Piña', drivers_name: 'R-Pinaa'  },
#     { email: 'Aristidesseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Aristides', last_name: 'Sevilla', drivers_name: 'sevillaleman'  },
#     { email: 'Christianseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Christian', last_name: 'Carrizo', drivers_name: 'PumpedbyCarry'  },
#     { email: 'Jeremyseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Jeremy', last_name: 'Cerda', drivers_name: 'Jeeremcg'  },
#     { email: 'Nicolásseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Nicolás', last_name: 'Alvarado', drivers_name: 'cheddars'  },
#     { email: 'Cesarseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Cesar', last_name: 'Aravena', drivers_name: 'Sokar09gg'  },
#     { email: 'Yonathanseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Yonathan', last_name: 'Morales', drivers_name: 'Kaito257'  },
#     { email: 'Marcoseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Marco', last_name: 'Bravo', drivers_name: 'marcoltr'  },
#     { email: 'Nicolasseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Nicolas', last_name: 'Pinto', drivers_name: 'pintroll68'  },
#     { email: 'Benjamínseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Benjamín', last_name: 'Contreras', drivers_name: 'Benjaaaaav7'  },
#     { email: 'Matiasseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Matias', last_name: 'Vega', drivers_name: 'Vazul311452'  },
#     { email: 'Arielseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Ariel', last_name: 'Fodor', drivers_name: 'Pearlykindom'  },
#     { email: 'Sebastianseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Sebastian', last_name: 'Montaner', drivers_name: 'tatanmontaner'  },
#     { email: 'Matíasseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Matías', last_name: 'Hernández', drivers_name: 'Df1c_elshishi24k'  },
#     { email: 'Vicenteseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Vicente', last_name: 'Torres', drivers_name: 'vicentetorres271'  },
#     { email: 'Maximilianoseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Maximiliano', last_name: 'Quiroz', drivers_name: 'maxiquiroz'  },
#     { email: 'Davidseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'David', last_name: 'Rencoret', drivers_name: 'RVR_DaviidR9'  },
#     { email: 'Gonzaloseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Gonzalo', last_name: 'Gana', drivers_name: 'Bart_sinso_666'  },
#     { email: 'Clementeseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Clemente', last_name: 'Schmidt', drivers_name: 'Cleme__F1'  },
#     { email: 'Fernandoseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Fernando', last_name: 'Naipil', drivers_name: 'Rayder7650'  },
#     { email: 'Pabloseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Pablo', last_name: 'Jerez', drivers_name: 'Pabloskyf1'  },
#     { email: 'Efrainseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Efrain', last_name: 'Rojas', drivers_name: 'Efrainrojas_Ers'  },
#     { email: 'Mauroseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Mauro', last_name: 'Araya', drivers_name: 'Mauro_A224'  },
#     { email: 'Nicolasseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Nicolas', last_name: 'Cabezas', drivers_name: 'Nikojr-2006'  },
#     { email: 'Felipeseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Felipe', last_name: 'Carlovich', drivers_name: 'Stylish_stratum9'  },
#     { email: 'Enzoseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Enzo', last_name: 'Guerrero', drivers_name: 'enzojgg08'  },
#     { email: 'Nicolásseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Nicolás', last_name: 'Salas', drivers_name: 'Naikoo_SD'  },
#     { email: 'Danielseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Daniel', last_name: 'Vera', drivers_name: 'RVR_Vera-A7X'  },
#     { email: 'Hamzahseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Hamzah', last_name: 'Shahid', drivers_name: 'Hamzah_shahid'  },
#     { email: 'Johatanseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Johatan', last_name: 'Gomez', drivers_name: 'Johatan_Gomez'  },
#     { email: 'Martinseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Martin', last_name: 'correa', drivers_name: 'Aire-fresco0'  },
#     { email: 'Sashaseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Sasha', last_name: 'Cassano', drivers_name: 'Sasha13485'  },
#     { email: 'Ignacioseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Ignacio', last_name: 'Espinoza', drivers_name: 'Inohcanoss'  },
#     { email: 'Cristianseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Cristian', last_name: 'Arancibia', drivers_name: 'Vanchris23'  },
#     { email: 'Arielseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Ariel', last_name: 'Alvear', drivers_name: 'aialvear'  },
#     { email: 'Diegoseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Diego', last_name: 'Flores', drivers_name: 'Diego1234_D'  },
#     { email: 'Sebastiánseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Sebastián', last_name: 'Maluenda', drivers_name: 'SEBA-MALUENDA17'  },
#     { email: 'Diegoseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Diego', last_name: 'Henriquez', drivers_name: 'Dihenriquezm'  },
#     { email: 'Gustavoseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Gustavo', last_name: 'Contreras', drivers_name: 'Gustaviho_oficia'  },
#     { email: 'Sebastiánseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Sebastián', last_name: 'Gallardo', drivers_name: 'Seba-_Albo2'  },
#     { email: 'Ciroseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Ciro', last_name: 'Zurita', drivers_name: 'Ciro_2411'  },
#     { email: 'Marioseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Mario', last_name: 'Urrutia', drivers_name: 'mrourrutia'  },
#     { email: 'Simónseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Simón', last_name: 'Ribó', drivers_name: 'xRIboh'  },
#     { email: 'Franciscoseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Francisco', last_name: 'Campos', drivers_name: 'PEEK_Pacomx1'  },
#     { email: 'Rodrigoseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Rodrigo', last_name: 'Espinosa', drivers_name: 'rorro_espinosa12'  },
#     { email: 'Aldoseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Aldo', last_name: 'Recabarren', drivers_name: '???'  },
#     { email: 'Sebastiánseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Sebastián', last_name: 'Tavella', drivers_name: 'Tachi2003'  },
#     { email: 'Alonsoseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Alonso', last_name: 'Delgado', drivers_name: 'XTHE_RIAL_ALONX'  },
#     { email: 'Benjamínseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Benjamín', last_name: 'Quiñones', drivers_name: 'theUnforgottn'  },
#     { email: 'Nicolasseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Nicolas', last_name: 'Álvarez', drivers_name: 'Liln1cx3'  },
#     { email: 'Matíasseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Matías', last_name: 'Carrasco', drivers_name: 'McCotona'  },
#     { email: 'Christopherseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Christopher', last_name: 'Compley', drivers_name: 'Kiiffer'  },
#     { email: 'Samuelseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Samuel', last_name: 'Salas', drivers_name: 'Samuelsalassep'  },
#     { email: 'Raúlseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Raúl', last_name: 'Reyes', drivers_name: 'Rau'  },
#     { email: 'Gabrielseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Gabriel', last_name: 'Galleguillos', drivers_name: 'Gabox_G'  },
#     { email: 'Rafaelseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Rafael', last_name: 'Barrios', drivers_name: 'RafaSsi'  },
#     { email: 'Juanseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Juan', last_name: 'Semino', drivers_name: 'Juanse'  },
#     { email: 'Mathiasseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Mathias', last_name: 'Huelmo', drivers_name: 'MathiasHuelmo'  },
#     { email: 'Álvaroseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Álvaro', last_name: 'Fuentes', drivers_name: 'Cabezon'  },
#     { email: 'Rodrigoseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Rodrigo', last_name: 'Leyton', drivers_name: 'SassoS'  },
#     { email: 'Alexandraseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Alexandra', last_name: 'Fernández', drivers_name: 'Alexa'  },
#     { email: 'Ivánseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Iván', last_name: 'Silva', drivers_name: 'Arquivan'  },
#     { email: 'Nicolásseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Nicolás', last_name: 'Roldán', drivers_name: 'leRoldi'  },
#     { email: 'Sebastiánseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Sebastián', last_name: 'Droguett', drivers_name: 'Drogson'  },
#     { email: 'Adriánseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Adrián', last_name: 'Puentes', drivers_name: 'Duffeld'  },
#     { email: 'Estanislaoseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Estanislao', last_name: 'Guerra', drivers_name: 'TANO'  },
#     { email: 'Francoseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Franco', last_name: 'Occhipinti', drivers_name: 'Franstuf'  },
#     { email: 'Diegoseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Diego', last_name: 'Salas', drivers_name: 'Chibi'  },
#     { email: 'Vicenteseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Vicente', last_name: 'Martinez', drivers_name: 'Belegsul'  },
#     { email: 'Leandroseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Leandro', last_name: 'Sánchez', drivers_name: 'leandro el x'  },
#     { email: 'Joaquínseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Joaquín', last_name: 'Rodriguez', drivers_name: 'Nimphu'  },
#     { email: 'Davidseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'David', last_name: 'Mondaca', drivers_name: 'Davo'  },
#     { email: 'Ivánseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Iván', last_name: 'Pérez', drivers_name: 'Sgt | Choripan'  },
#     { email: 'Luisseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Luis', last_name: 'Pastine', drivers_name: 'PastineFTW'  },
#     { email: 'Aaronseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Aaron', last_name: 'Milera', drivers_name: 'MILERA'  },
#     { email: 'Richardseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Richard', last_name: 'Hernández', drivers_name: 'RichardHdez'  },
#     { email: 'Gonzaloseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Gonzalo', last_name: 'Toro', drivers_name: '4LIEN'  },
#     { email: 'Vicenteseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Vicente', last_name: 'Martín', drivers_name: 'TinkyWinky'  },
#     { email: 'Sebastiánseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Sebastián', last_name: 'Matheus', drivers_name: 'Svbs'  },
#     { email: 'Luisseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Luis', last_name: 'Blanco', drivers_name: 'RIXU'  },
#     { email: 'Jacobseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Jacob', last_name: 'Cubillos', drivers_name: 'Jeycob_Hs'  },
#     { email: 'Michaelseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Michael', last_name: 'Winstanley', drivers_name: 'Wins'  },
#     { email: 'Felipeseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Felipe', last_name: 'Ortiz', drivers_name: 'Pipezinho'  },
#     { email: 'Maxiseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Maxi', last_name: 'Ortiz', drivers_name: 'Tuki'  },
#     { email: 'Cristóbalseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Cristóbal', last_name: 'Barra-Cisterna', drivers_name: 'CrisBC'  },
#     { email: 'Felipeseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Felipe', last_name: 'Villalobos', drivers_name: 'Visha'  },
#     { email: 'Nicolásseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Nicolás', last_name: 'Roldán', drivers_name: 'leRoldi'  },
#     { email: 'Álvaroseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Álvaro', last_name: 'Fuentes', drivers_name: 'Cabezon'  },
#     { email: 'Ivánseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Iván', last_name: 'Pérez', drivers_name: 'Sgt | Choripan'  },
#     { email: 'Luisseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Luis', last_name: 'Blanco', drivers_name: 'Rixu'  },
#     { email: 'Richardseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Richard', last_name: 'Hernández', drivers_name: 'RichardHdez'  },
#     { email: 'Leandroseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Leandro', last_name: 'Sanchez', drivers_name: 'Leandro el x'  },
#     { email: 'Manuelseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Manuel', last_name: 'Mandiola', drivers_name: 'Manuus'  },
#     { email: 'Sebastiánseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Sebastián', last_name: 'Estrada', drivers_name: 'StradaSSL'  },
#     { email: 'Sebastiánseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Sebastián', last_name: 'Droguett', drivers_name: 'Drogson'  },
#     { email: 'Manuelseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Manuel', last_name: 'Wu', drivers_name: 'Manuel Wu'  },
#     { email: 'Aaronseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Aaron', last_name: 'Milera', drivers_name: 'MILERA'  },
#     { email: 'Luisseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Luis', last_name: 'Pastine', drivers_name: 'PastineFTW'  },
#     { email: 'Vicenteseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Vicente', last_name: 'Martín', drivers_name: 'TinkyWinky'  },
#     { email: 'Manuelseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Manuel', last_name: 'Hidalgo', drivers_name: 'Manolenkix'  },
#     { email: 'Sebastiánseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Sebastián', last_name: 'Matheus', drivers_name: 'Svbs'  },
#     { email: 'Felipeseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Felipe', last_name: 'Ortiz', drivers_name: 'Pipezinho'  },
#     { email: 'Rodrigoseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Rodrigo', last_name: 'Leyton', drivers_name: 'SassoS'  },
#     { email: 'Vicenteseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Vicente', last_name: 'Martinez', drivers_name: 'Belegsul'  },
#     { email: 'Adriánseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Adrián', last_name: 'Puentes', drivers_name: 'Duffeld'  },
#     { email: 'Matíasseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Matías', last_name: 'Burton', drivers_name: 'Mati.Burton'  },
#     { email: 'Maxiseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Maxi', last_name: 'Ortiz', drivers_name: 'Tuki'  },
#     { email: 'Felipeseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Felipe', last_name: 'Ponce', drivers_name: 'Lukanoth'  },
#     { email: 'Douglasseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Douglas', last_name: 'Rodriguez', drivers_name: 'Meeiko'  },
#     { email: 'Emilioseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Emilio', last_name: 'Martinez', drivers_name: 'Emi'  },
#     { email: 'Francoseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Franco', last_name: 'Zapata', drivers_name: 'Pasas de Uva'  },
#     { email: 'Eduardoseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Eduardo', last_name: 'Castillo', drivers_name: 'TR Castillo'  },
#     { email: 'Matíasseed@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Matías', last_name: 'Figueroa', drivers_name: 'Matix'  },
#   ]
# )
