# # # # Crear usuarios
# # # User.destroy_all

User.create(
              [
                {
                  email: 'ariel@liga.cl',
                  password: '12345678',
                  name: 'ariel',
                  last_name: 'alvear',
                  drivers_name: 'aialvear',
                },
                {
                  email: 'juan@liga.cl',
                  password: '12345678',
                  name: 'juan',
                  last_name: 'perez',
                  drivers_name: 'juano',
                },
                {
                  email: 'pedro@liga.cl',
                  password: '12345678',
                  name: 'pedro',
                  last_name: 'hernandez',
                  drivers_name: 'peter',
                },
              ]
            )

# User.create(
#   [
#     { email: 'Benjamindummy@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Benjamin', last_name: 'Salazar', drivers_name: 'RVR_Minchito'  },
#     { email: 'Matiasdummy@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Matias', last_name: 'Matamala', drivers_name: 'ManUtdFans14'  },
#     { email: 'Nicolasdummy@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Nicolas', last_name: 'Lagos', drivers_name: 'RVR_Nicolas10'  },
#     { email: 'JuanPablodummy@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'JuanPablo', last_name: 'Morales', drivers_name: 'RPFunky'  },
#     { email: 'Maximilianodummy@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Maximiliano', last_name: 'Heredia', drivers_name: 'Mazzi1991'  },
#     { email: 'Maximilianodummy@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Maximiliano', last_name: 'Tomic', drivers_name: 'Maxtomic'  },
#     { email: 'Matiasdummy@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Matias', last_name: 'Pino', drivers_name: 'Matrenox'  },
#     { email: 'Jesusdummy@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Jesus', last_name: 'Rios', drivers_name: 'Pepechuy12'  },
#     { email: 'Alfonsodummy@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Alfonso', last_name: 'Urbina', drivers_name: 'xAlf0ns07x'  },
#     { email: 'Lucasdummy@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Lucas', last_name: 'Riveras', drivers_name: 'LUKA_THE_PRO'  },
#     { email: 'Cristobaldummy@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Cristobal', last_name: 'Figueroa', drivers_name: 'Crisafm'  },
#     { email: 'Andresdummy@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Andres', last_name: 'Mendez', drivers_name: 'Amendez53444'  },
#     { email: 'Juandummy@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Juan', last_name: 'Valdivia', drivers_name: 'NazhonxX'  },
#     { email: 'Robertodummy@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Roberto', last_name: 'Manriquez', drivers_name: 'RoLo-_-gg'  },
#     { email: 'Martindummy@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Martin', last_name: 'Orellana', drivers_name: 'faZe_Titi'  },
#     { email: 'Aristidesdummy@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Aristides', last_name: 'Sevilla', drivers_name: 'sevillaleman'  },
#     { email: 'Christiandummy@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Christian', last_name: 'Carrizo', drivers_name: 'PumpedbyCarry'  },
#     { email: 'Nicolásdummy@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Nicolás', last_name: 'Alvarado', drivers_name: 'cheddars'  },
#     { email: 'Cesardummy@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Cesar', last_name: 'Aravena', drivers_name: 'Sokar09gg'  },
#     { email: 'Yonathandummy@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Yonathan', last_name: 'Morales', drivers_name: 'Kaito257'  },
#     { email: 'Marcodummy@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Marco', last_name: 'Bravo', drivers_name: 'marcoltr'  },
#     { email: 'Nicolasdummy@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Nicolas', last_name: 'Pinto', drivers_name: 'pintroll68'  },
#     { email: 'Benjamíndummy@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Benjamín', last_name: 'Contreras', drivers_name: 'Benjaaaaav7'  },
#     { email: 'Matiasdummy@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Matias', last_name: 'Vega', drivers_name: 'Vazul311452'  },
#     { email: 'Arieldummy@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Ariel', last_name: 'Fodor', drivers_name: 'Pearlykindom'  },
#     { email: 'Sebastiandummy@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Sebastian', last_name: 'Montaner', drivers_name: 'tatanmontaner'  },
#     { email: 'Matíasdummy@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Matías', last_name: 'Hernández', drivers_name: 'Df1c_elshishi24k'  },
#     { email: 'Vicentedummy@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Vicente', last_name: 'Torres', drivers_name: 'vicentetorres271'  },
#     { email: 'Maximilianodummy@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Maximiliano', last_name: 'Quiroz', drivers_name: 'maxiquiroz'  },
#     { email: 'Daviddummy@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'David', last_name: 'Rencoret', drivers_name: 'RVR_DaviidR9'  },
#     { email: 'Gonzalodummy@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Gonzalo', last_name: 'Gana', drivers_name: 'Bart_sinso_666'  },
#     { email: 'Clementedummy@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Clemente', last_name: 'Schmidt', drivers_name: 'Cleme__F1'  },
#     { email: 'Fernandodummy@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Fernando', last_name: 'Naipil', drivers_name: 'Rayder7650'  },
#     { email: 'Efraindummy@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Efrain', last_name: 'Rojas', drivers_name: 'Efrainrojas_Ers'  },
#     { email: 'Maurodummy@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Mauro', last_name: 'Araya', drivers_name: 'Mauro_A224'  },
#     { email: 'Nicolasdummy@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Nicolas', last_name: 'Cabezas', drivers_name: 'Nikojr-2006'  },
#     { email: 'Felipedummy@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Felipe', last_name: 'Carlovich', drivers_name: 'Stylish_stratum9'  },
#     { email: 'Enzodummy@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Enzo', last_name: 'Guerrero', drivers_name: 'enzojgg08'  },
#     { email: 'Nicolásdummy@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Nicolás', last_name: 'Salas', drivers_name: 'Naikoo_SD'  },
#     { email: 'Hamzahdummy@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Hamzah', last_name: 'Shahid', drivers_name: 'Hamzah_shahid'  },
#     { email: 'Johatandummy@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Johatan', last_name: 'Gomez', drivers_name: 'Johatan_Gomez'  },
#     { email: 'Martindummy@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Martin', last_name: 'correa', drivers_name: 'Aire-fresco0'  },
#     { email: 'Sashadummy@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Sasha', last_name: 'Cassano', drivers_name: 'Sasha13485'  },
#     { email: 'Ignaciodummy@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Ignacio', last_name: 'Espinoza', drivers_name: 'Inohcanoss'  },
#     { email: 'Diegodummy@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Diego', last_name: 'Flores', drivers_name: 'Diego1234_D'  },
#     { email: 'Sebastiándummy@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Sebastián', last_name: 'Maluenda', drivers_name: 'SEBA-MALUENDA17'  },
#     { email: 'Diegodummy@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Diego', last_name: 'Henriquez', drivers_name: 'Dihenriquezm'  },
#     { email: 'Gustavodummy@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Gustavo', last_name: 'Contreras', drivers_name: 'Gustaviho_oficia'  },
#     { email: 'Sebastiándummy@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Sebastián', last_name: 'Gallardo', drivers_name: 'Seba-_Albo2'  },
#     { email: 'Cirodummy@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Ciro', last_name: 'Zurita', drivers_name: 'Ciro_2411'  },
#     { email: 'Mariodummy@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Mario', last_name: 'Urrutia', drivers_name: 'mrourrutia'  },
#     { email: 'Simóndummy@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Simón', last_name: 'Ribó', drivers_name: 'xRIboh'  },
#     { email: 'Franciscodummy@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Francisco', last_name: 'Campos', drivers_name: 'PEEK_Pacomx1'  },
#     { email: 'Rodrigodummy@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Rodrigo', last_name: 'Espinosa', drivers_name: 'rorro_espinosa12'  },
#     { email: 'Aldodummy@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Aldo', last_name: 'Recabarren', drivers_name: '???'  },
#     { email: 'Sebastiándummy@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Sebastián', last_name: 'Tavella', drivers_name: 'Tachi2003'  },
#     { email: 'Alonsodummy@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Alonso', last_name: 'Delgado', drivers_name: 'XTHE_RIAL_ALONX'  },
#     { email: 'Benjamíndummy@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Benjamín', last_name: 'Quiñones', drivers_name: 'theUnforgottn'  },
#     { email: 'Nicolasdummy@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Nicolas', last_name: 'Álvarez', drivers_name: 'Liln1cx3'  },
#     { email: 'Matíasdummy@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Matías', last_name: 'Carrasco', drivers_name: 'McCotona'  },
#     { email: 'Christopherdummy@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Christopher', last_name: 'Compley', drivers_name: 'Kiiffer'  },
#     { email: 'Samueldummy@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Samuel', last_name: 'Salas', drivers_name: 'Samuelsalassep'  },
#     { email: 'Raúldummy@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Raúl', last_name: 'Reyes', drivers_name: 'Rau'  },
#     { email: 'Gabrieldummy@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Gabriel', last_name: 'Galleguillos', drivers_name: 'Gabox_G'  },
#     { email: 'Rafaeldummy@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Rafael', last_name: 'Barrios', drivers_name: 'RafaSsi'  },
#     { email: 'Juandummy@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Juan', last_name: 'Semino', drivers_name: 'Juanse'  },
#     { email: 'Mathiasdummy@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Mathias', last_name: 'Huelmo', drivers_name: 'MathiasHuelmo'  },
#     { email: 'Álvarodummy@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Álvaro', last_name: 'Fuentes', drivers_name: 'Cabezon'  },
#     { email: 'Rodrigodummy@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Rodrigo', last_name: 'Leyton', drivers_name: 'SassoS'  },
#     { email: 'Alexandradummy@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Alexandra', last_name: 'Fernández', drivers_name: 'Alexa'  },
#     { email: 'Ivándummy@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Iván', last_name: 'Silva', drivers_name: 'Arquivan'  },
#     { email: 'Nicolásdummy@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Nicolás', last_name: 'Roldán', drivers_name: 'leRoldi'  },
#     { email: 'Sebastiándummy@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Sebastián', last_name: 'Droguett', drivers_name: 'Drogson'  },
#     { email: 'Adriándummy@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Adrián', last_name: 'Puentes', drivers_name: 'Duffeld'  },
#     { email: 'Estanislaodummy@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Estanislao', last_name: 'Guerra', drivers_name: 'TANO'  },
#     { email: 'Francodummy@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Franco', last_name: 'Occhipinti', drivers_name: 'Franstuf'  },
#     { email: 'Diegodummy@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Diego', last_name: 'Salas', drivers_name: 'Chibi'  },
#     { email: 'Vicentedummy@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Vicente', last_name: 'Martinez', drivers_name: 'Belegsul'  },
#     { email: 'Leandrodummy@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Leandro', last_name: 'Sánchez', drivers_name: 'leandro el x'  },
#     { email: 'Joaquíndummy@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Joaquín', last_name: 'Rodriguez', drivers_name: 'Nimphu'  },
#     { email: 'Daviddummy@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'David', last_name: 'Mondaca', drivers_name: 'Davo'  },
#     { email: 'Ivándummy@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Iván', last_name: 'Pérez', drivers_name: 'Sgt | Choripan'  },
#     { email: 'Luisdummy@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Luis', last_name: 'Pastine', drivers_name: 'PastineFTW'  },
#     { email: 'Aarondummy@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Aaron', last_name: 'Milera', drivers_name: 'MILERA'  },
#     { email: 'Richarddummy@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Richard', last_name: 'Hernández', drivers_name: 'RichardHdez'  },
#     { email: 'Gonzalodummy@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Gonzalo', last_name: 'Toro', drivers_name: '4LIEN'  },
#     { email: 'Vicentedummy@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Vicente', last_name: 'Martín', drivers_name: 'TinkyWinky'  },
#     { email: 'Sebastiándummy@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Sebastián', last_name: 'Matheus', drivers_name: 'Svbs'  },
#     { email: 'Luisdummy@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Luis', last_name: 'Blanco', drivers_name: 'RIXU'  },
#     { email: 'Jacobdummy@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Jacob', last_name: 'Cubillos', drivers_name: 'Jeycob_Hs'  },
#     { email: 'Michaeldummy@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Michael', last_name: 'Winstanley', drivers_name: 'Wins'  },
#     { email: 'Felipedummy@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Felipe', last_name: 'Ortiz', drivers_name: 'Pipezinho'  },
#     { email: 'Maxidummy@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Maxi', last_name: 'Ortiz', drivers_name: 'Tuki'  },
#     { email: 'Cristóbaldummy@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Cristóbal', last_name: 'Barra-Cisterna', drivers_name: 'CrisBC'  },
#     { email: 'Felipedummy@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Felipe', last_name: 'Villalobos', drivers_name: 'Visha'  },
#     { email: 'Nicolásdummy@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Nicolás', last_name: 'Roldán', drivers_name: 'leRoldi'  },
#     { email: 'Álvarodummy@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Álvaro', last_name: 'Fuentes', drivers_name: 'Cabezon'  },
#     { email: 'Ivándummy@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Iván', last_name: 'Pérez', drivers_name: 'Sgt | Choripan'  },
#     { email: 'Luisdummy@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Luis', last_name: 'Blanco', drivers_name: 'Rixu'  },
#     { email: 'Richarddummy@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Richard', last_name: 'Hernández', drivers_name: 'RichardHdez'  },
#     { email: 'Leandrodummy@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Leandro', last_name: 'Sanchez', drivers_name: 'Leandro el x'  },
#     { email: 'Manueldummy@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Manuel', last_name: 'Mandiola', drivers_name: 'Manuus'  },
#     { email: 'Sebastiándummy@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Sebastián', last_name: 'Estrada', drivers_name: 'StradaSSL'  },
#     { email: 'Sebastiándummy@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Sebastián', last_name: 'Droguett', drivers_name: 'Drogson'  },
#     { email: 'Manueldummy@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Manuel', last_name: 'Wu', drivers_name: 'Manuel Wu'  },
#     { email: 'Aarondummy@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Aaron', last_name: 'Milera', drivers_name: 'MILERA'  },
#     { email: 'Luisdummy@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Luis', last_name: 'Pastine', drivers_name: 'PastineFTW'  },
#     { email: 'Vicentedummy@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Vicente', last_name: 'Martín', drivers_name: 'TinkyWinky'  },
#     { email: 'Manueldummy@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Manuel', last_name: 'Hidalgo', drivers_name: 'Manolenkix'  },
#     { email: 'Sebastiándummy@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Sebastián', last_name: 'Matheus', drivers_name: 'Svbs'  },
#     { email: 'Felipedummy@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Felipe', last_name: 'Ortiz', drivers_name: 'Pipezinho'  },
#     { email: 'Rodrigodummy@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Rodrigo', last_name: 'Leyton', drivers_name: 'SassoS'  },
#     { email: 'Vicentedummy@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Vicente', last_name: 'Martinez', drivers_name: 'Belegsul'  },
#     { email: 'Adriándummy@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Adrián', last_name: 'Puentes', drivers_name: 'Duffeld'  },
#     { email: 'Matíasdummy@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Matías', last_name: 'Burton', drivers_name: 'Mati.Burton'  },
#     { email: 'Maxidummy@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Maxi', last_name: 'Ortiz', drivers_name: 'Tuki'  },
#     { email: 'Felipedummy@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Felipe', last_name: 'Ponce', drivers_name: 'Lukanoth'  },
#     { email: 'Douglasdummy@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Douglas', last_name: 'Rodriguez', drivers_name: 'Meeiko'  },
#     { email: 'Emiliodummy@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Emilio', last_name: 'Martinez', drivers_name: 'Emi'  },
#     { email: 'Francodummy@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Franco', last_name: 'Zapata', drivers_name: 'Pasas de Uva'  },
#     { email: 'Matíasdummy@liga.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Matías', last_name: 'Figueroa', drivers_name: 'Matix'  },
#   ]
# )
