# # # # # Crear usuarios
# # # # User.destroy_all

User.create(
              [
  { email: 'TANO@ligaF1Chile.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Estanislao', last_name: 'Guerra', drivers_name: 'TANO'  },
  { email: 'Duffeld@ligaF1Chile.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Adrián', last_name: 'Puentes', drivers_name: 'Duffeld'  },
  { email: 'Rau@ligaF1Chile.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Raúl', last_name: 'Reyes', drivers_name: 'Rau'  },
  { email: '4LIEN@ligaF1Chile.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Gonzalo', last_name: 'Toro', drivers_name: '4LIEN'  },
  { email: 'Drogson@ligaF1Chile.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Sebastián', last_name: 'Droguett', drivers_name: 'Drogson'  },
  { email: 'Chibi@ligaF1Chile.cl', password: 'diego1', name: 'Diego', last_name: 'Salas', drivers_name: 'Chibi'  },
  { email: 'Alexa@ligaF1Chile.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Alexandra', last_name: 'Fernández', drivers_name: 'Alexa'  },
  { email: 'Nimphu@ligaF1Chile.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Joaquín', last_name: 'Rodríguez', drivers_name: 'Nimphu'  },
  { email: 'SassoS@ligaF1Chile.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Rodrigo', last_name: 'Leyton', drivers_name: 'SassoS'  },
  { email: 'RafaSsi@ligaF1Chile.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Rafael', last_name: 'Barrios', drivers_name: 'RafaSsi'  },
  { email: 'Choripan@ligaF1Chile.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Iván', last_name: 'Pérez', drivers_name: 'Choripan'  },
  { email: 'MathiasHuelmo@ligaF1Chile.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Mathias', last_name: 'Huelmo', drivers_name: 'MathiasHuelmo'  },
  { email: 'leRoldi@ligaF1Chile.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Nicolás', last_name: 'Roldán', drivers_name: 'leRoldi'  },
  { email: 'RichardHdez@ligaF1Chile.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Richard', last_name: 'Hernández', drivers_name: 'RichardHdez'  },
  { email: 'Cabezon@ligaF1Chile.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Álvaro', last_name: 'Fuentes', drivers_name: 'Cabezon'  },
  { email: 'leandro el x@ligaF1Chile.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Leandro', last_name: 'Sánchez', drivers_name: 'leandro el x'  },
  { email: 'Rixu@ligaF1Chile.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Luis', last_name: 'Blanco', drivers_name: 'Rixu'  },
  { email: 'Mati.Burton@ligaF1Chile.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Matías', last_name: 'Burton', drivers_name: 'Mati.Burton'  },
  { email: 'Meeiko@ligaF1Chile.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Douglas', last_name: 'Rodríguez', drivers_name: 'Meeiko'  },
  { email: 'LuisPastine@ligaF1Chile.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Luis', last_name: 'Pastine', drivers_name: 'LuisPastine'  },
  { email: 'Bvenjao@ligaF1Chile.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Benjamin', last_name: 'Huenchu', drivers_name: 'Bvenjao'  },
  { email: 'Tuki@ligaF1Chile.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Maxi', last_name: 'Ortiz', drivers_name: 'Tuki'  },
  { email: 'Lukanoth@ligaF1Chile.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Felipe', last_name: 'Ponce', drivers_name: 'Lukanoth'  },
  { email: 'Manuus@ligaF1Chile.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Manuel', last_name: 'Mandiola', drivers_name: 'Manuus'  },
  { email: 'Jeycob_HS@ligaF1Chile.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Jacob', last_name: 'Cubillos', drivers_name: 'Jeycob_HS'  },
  { email: 'CrisBC@ligaF1Chile.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Cristóbal', last_name: 'Barra-Cisterna', drivers_name: 'CrisBC'  },
  { email: 'Manolenkix@ligaF1Chile.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Manuel', last_name: 'Hidalgo', drivers_name: 'Manolenkix'  },
  { email: 'MILERA@ligaF1Chile.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Aaron', last_name: 'Milera', drivers_name: 'MILERA'  },
  { email: 'Emi@ligaF1Chile.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Emilio', last_name: 'Martínez', drivers_name: 'Emi'  },
  { email: 'Davo@ligaF1Chile.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'David', last_name: 'Elizarraraz', drivers_name: 'Davo'  },
  { email: 'Pipezinho@ligaF1Chile.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Felipe', last_name: 'Ortiz', drivers_name: 'Pipezinho'  },
  { email: '$trada@ligaF1Chile.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Sebastián', last_name: 'Estrada', drivers_name: '$trada'  },
  { email: 'Svbs@ligaF1Chile.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Sebastián', last_name: 'Matheus', drivers_name: 'Svbs'  },
  { email: 'Belegsul@ligaF1Chile.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Vicente', last_name: 'Martinez', drivers_name: 'Belegsul'  },
  { email: 'TinkyWinky@ligaF1Chile.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Vicente', last_name: 'Martín', drivers_name: 'TinkyWinky'  },
  { email: 'Wu@ligaF1Chile.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Manuel', last_name: 'Wu', drivers_name: 'Wu'  },
  { email: 'Arquivan@ligaF1Chile.cl', password: 'ansflasnfkanfkanfkasfnalkfasf!', name: 'Iván', last_name: 'Silva', drivers_name: 'Arquivan'  },
              ]
            )
