# # Listado de pistas de F1 2021

# Track.find_or_create_by(id: 1, name: "Bahrain International Circuit", country: "Barein")
# Track.find_or_create_by(id: 2, name: "Autódromo Enzo e Dino Ferrari", country: "Italia")
# Track.find_or_create_by(id: 3, name: "Circuito Internacional del Algarve", country: "Portugal")
# Track.find_or_create_by(id: 4, name: "Circuit de Barcelona-Catalunya", country: "España")
# Track.find_or_create_by(id: 5, name: "Circuit de Monaco", country: "Monaco")
# Track.find_or_create_by(id: 6, name: "Baku City Circuit", country: "Azerbaiyan")
# Track.find_or_create_by(id: 7, name: "Circuit Paul Ricard", country: "Francia")
# Track.find_or_create_by(id: 8, name: "Red Bull Ring", country: "Austria")
# Track.find_or_create_by(id: 9, name: "Silverstone Circuit", country: "Reino Unido")
# Track.find_or_create_by(id: 10, name: "Hungaroring", country: "Hungría")
# Track.find_or_create_by(id: 11, name: "Circuit de Spa-Francorchamps", country: "Bélgica")
# Track.find_or_create_by(id: 12, name: "Circuit Zandvoort", country: "Países Bajos")
# Track.find_or_create_by(id: 13, name: "Autodromo Nazionale di Monza", country: "Italia")
# Track.find_or_create_by(id: 14, name: "Sochi Autodrom", country: "Rusia")
# Track.find_or_create_by(id: 15, name: "Marina Bay Street Circuit", country: "Singapur")
# Track.find_or_create_by(id: 16, name: "Suzuka International Racing Course", country: "Japon")
# Track.find_or_create_by(id: 17, name: "Circuit of The Americas", country: "EEUU")
# Track.find_or_create_by(id: 18, name: "Autódromo Hermanos Rodríguez", country: "Mexico")
# Track.find_or_create_by(id: 19, name: "Autódromo José Carlos Pace", country: "Brasil")
# Track.find_or_create_by(id: 20, name: "Albert Park Circuit", country: "Australia")
# Track.find_or_create_by(id: 21, name: "Al-Diriyah Circuit", country: "Arabia Saudita")
# Track.find_or_create_by(id: 22, name: "Yas Marina Circuit", country: "Abu Dabi")
