# Listado de pistas de F1 2021

Track.find_or_create_by(id: 1, name: "Sakhir", country: "Bahréin")
Track.find_or_create_by(id: 2, name: "Imola", country: "Italia")
Track.find_or_create_by(id: 3, name: "Portimao", country: "Portugal")
Track.find_or_create_by(id: 4, name: "Barcelona", country: "España")
Track.find_or_create_by(id: 5, name: "Monte Carlo", country: "Mónaco")
Track.find_or_create_by(id: 6, name: "Bakú", country: "Azebaián")
Track.find_or_create_by(id: 7, name: "Paul Ricard", country: "Francia")
Track.find_or_create_by(id: 8, name: "Red Bull Ring", country: "Austria")
Track.find_or_create_by(id: 9, name: "Silverstone", country: "Gran Bretaña")
Track.find_or_create_by(id: 10, name: "Hungaroring", country: "Hungría")
Track.find_or_create_by(id: 11, name: "Spa-Francorchamps", country: "Bélgica")
Track.find_or_create_by(id: 12, name: "Zandvoort", country: "Países Bajos")
Track.find_or_create_by(id: 13, name: "Monza", country: "Italia")
Track.find_or_create_by(id: 14, name: "Sochi", country: "Rusia")
Track.find_or_create_by(id: 15, name: "Suzuka", country: "Japón")
Track.find_or_create_by(id: 16, name: "Austin", country: "Estados Unidos")
Track.find_or_create_by(id: 17, name: "Hermanos Rodríguez", country: "México")
Track.find_or_create_by(id: 18, name: "Interlagos", country: "Brasil")
Track.find_or_create_by(id: 19, name: "Jeddah", country: "Arabia Saudí")
Track.find_or_create_by(id: 20, name: "Yas Marina", country: "Abu Dhabi")
